# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170703_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=4096)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histograms', to='core.MediaFile')),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.MediaFile'),
        ),
    ]
