# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediafile_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='flip',
            field=models.NullBooleanField(),
        ),
    ]
