# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170708_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['full_path']},
        ),
    ]
