# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170709_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='full_path',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='digest',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='mime_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='path',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
