# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170709_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
