# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mediafile_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['recorded']},
        ),
    ]
