# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170716_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={},
        ),
        migrations.AddField(
            model_name='location',
            name='geocode',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
