# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170718_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstrip',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
