# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
