# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170728_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='palette',
            options={'ordering': ['-prominence']},
        ),
        migrations.AlterField(
            model_name='face',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='core.Person'),
        ),
    ]
