// flow-typed signature: 0d1e7b0e52429557aa69e3cd85d26e6e
// flow-typed version: <<STUB>>/@meadow/redux-ensure-fsa_v^2.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@meadow/redux-ensure-fsa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@meadow/redux-ensure-fsa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@meadow/redux-ensure-fsa/build/middleware' {
  declare module.exports: any;
}

declare module '@meadow/redux-ensure-fsa/modules/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module '@meadow/redux-ensure-fsa/build/middleware.js' {
  declare module.exports: $Exports<'@meadow/redux-ensure-fsa/build/middleware'>;
}
declare module '@meadow/redux-ensure-fsa/modules/middleware.js' {
  declare module.exports: $Exports<'@meadow/redux-ensure-fsa/modules/middleware'>;
}
