// flow-typed signature: 0b61efa74736b722822c1135f7ea4d92
// flow-typed version: <<STUB>>/eslint-config-semistandard_v^11.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-semistandard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-semistandard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-semistandard/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-semistandard/index' {
  declare module.exports: $Exports<'eslint-config-semistandard'>;
}
declare module 'eslint-config-semistandard/index.js' {
  declare module.exports: $Exports<'eslint-config-semistandard'>;
}
declare module 'eslint-config-semistandard/test/index.js' {
  declare module.exports: $Exports<'eslint-config-semistandard/test/index'>;
}
