// flow-typed signature: f557ed12f572e5c46bdf295126d17594
// flow-typed version: <<STUB>>/format-duration_v^1.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'format-duration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'format-duration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'format-duration/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'format-duration/index' {
  declare module.exports: $Exports<'format-duration'>;
}
declare module 'format-duration/index.js' {
  declare module.exports: $Exports<'format-duration'>;
}
declare module 'format-duration/test/index.js' {
  declare module.exports: $Exports<'format-duration/test/index'>;
}
