// flow-typed signature: 4d7874c0f3ac1d4a90a813164160fee8
// flow-typed version: <<STUB>>/uikit_v^3.0.0-beta.27/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uikit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uikit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uikit/build/build' {
  declare module.exports: any;
}

declare module 'uikit/build/icons' {
  declare module.exports: any;
}

declare module 'uikit/build/less' {
  declare module.exports: any;
}

declare module 'uikit/build/prefix' {
  declare module.exports: any;
}

declare module 'uikit/build/release' {
  declare module.exports: any;
}

declare module 'uikit/build/scope' {
  declare module.exports: any;
}

declare module 'uikit/build/scss' {
  declare module.exports: any;
}

declare module 'uikit/build/util' {
  declare module.exports: any;
}

declare module 'uikit/dist/js/uikit-icons' {
  declare module.exports: any;
}

declare module 'uikit/dist/js/uikit-icons.min' {
  declare module.exports: any;
}

declare module 'uikit/dist/js/uikit' {
  declare module.exports: any;
}

declare module 'uikit/dist/js/uikit.min' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/boot' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/class' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/component' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/global' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/hooks' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/index' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/instance' {
  declare module.exports: any;
}

declare module 'uikit/src/js/api/state' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/countdown' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/grid-parallax' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/lightbox' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/notification' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/parallax' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/sortable' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/tooltip' {
  declare module.exports: any;
}

declare module 'uikit/src/js/components/upload' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/accordion' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/alert' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/cover' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/drop' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/dropdown' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/form-custom' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/gif' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/grid' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/height-match' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/height-viewport' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/hover' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/icon' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/index' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/leader' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/margin' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/modal' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/nav' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/navbar' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/offcanvas' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/responsive' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/scroll' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/scrollspy-nav' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/scrollspy' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/sticky' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/svg' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/switcher' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/tab' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/toggle' {
  declare module.exports: any;
}

declare module 'uikit/src/js/core/video' {
  declare module.exports: any;
}

declare module 'uikit/src/js/icons' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/class' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/index' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/modal' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/position' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/slideshow' {
  declare module.exports: any;
}

declare module 'uikit/src/js/mixin/togglable' {
  declare module.exports: any;
}

declare module 'uikit/src/js/uikit-core' {
  declare module.exports: any;
}

declare module 'uikit/src/js/uikit' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/dom' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/env' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/fastdom' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/index' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/lang' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/mouse' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/options' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/player' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/position' {
  declare module.exports: any;
}

declare module 'uikit/src/js/util/touch' {
  declare module.exports: any;
}

declare module 'uikit/tests/js/index' {
  declare module.exports: any;
}

declare module 'uikit/tests/js/uikit' {
  declare module.exports: any;
}

declare module 'uikit/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uikit/build/build.js' {
  declare module.exports: $Exports<'uikit/build/build'>;
}
declare module 'uikit/build/icons.js' {
  declare module.exports: $Exports<'uikit/build/icons'>;
}
declare module 'uikit/build/less.js' {
  declare module.exports: $Exports<'uikit/build/less'>;
}
declare module 'uikit/build/prefix.js' {
  declare module.exports: $Exports<'uikit/build/prefix'>;
}
declare module 'uikit/build/release.js' {
  declare module.exports: $Exports<'uikit/build/release'>;
}
declare module 'uikit/build/scope.js' {
  declare module.exports: $Exports<'uikit/build/scope'>;
}
declare module 'uikit/build/scss.js' {
  declare module.exports: $Exports<'uikit/build/scss'>;
}
declare module 'uikit/build/util.js' {
  declare module.exports: $Exports<'uikit/build/util'>;
}
declare module 'uikit/dist/js/uikit-icons.js' {
  declare module.exports: $Exports<'uikit/dist/js/uikit-icons'>;
}
declare module 'uikit/dist/js/uikit-icons.min.js' {
  declare module.exports: $Exports<'uikit/dist/js/uikit-icons.min'>;
}
declare module 'uikit/dist/js/uikit.js' {
  declare module.exports: $Exports<'uikit/dist/js/uikit'>;
}
declare module 'uikit/dist/js/uikit.min.js' {
  declare module.exports: $Exports<'uikit/dist/js/uikit.min'>;
}
declare module 'uikit/src/js/api/boot.js' {
  declare module.exports: $Exports<'uikit/src/js/api/boot'>;
}
declare module 'uikit/src/js/api/class.js' {
  declare module.exports: $Exports<'uikit/src/js/api/class'>;
}
declare module 'uikit/src/js/api/component.js' {
  declare module.exports: $Exports<'uikit/src/js/api/component'>;
}
declare module 'uikit/src/js/api/global.js' {
  declare module.exports: $Exports<'uikit/src/js/api/global'>;
}
declare module 'uikit/src/js/api/hooks.js' {
  declare module.exports: $Exports<'uikit/src/js/api/hooks'>;
}
declare module 'uikit/src/js/api/index.js' {
  declare module.exports: $Exports<'uikit/src/js/api/index'>;
}
declare module 'uikit/src/js/api/instance.js' {
  declare module.exports: $Exports<'uikit/src/js/api/instance'>;
}
declare module 'uikit/src/js/api/state.js' {
  declare module.exports: $Exports<'uikit/src/js/api/state'>;
}
declare module 'uikit/src/js/components/countdown.js' {
  declare module.exports: $Exports<'uikit/src/js/components/countdown'>;
}
declare module 'uikit/src/js/components/grid-parallax.js' {
  declare module.exports: $Exports<'uikit/src/js/components/grid-parallax'>;
}
declare module 'uikit/src/js/components/lightbox.js' {
  declare module.exports: $Exports<'uikit/src/js/components/lightbox'>;
}
declare module 'uikit/src/js/components/notification.js' {
  declare module.exports: $Exports<'uikit/src/js/components/notification'>;
}
declare module 'uikit/src/js/components/parallax.js' {
  declare module.exports: $Exports<'uikit/src/js/components/parallax'>;
}
declare module 'uikit/src/js/components/sortable.js' {
  declare module.exports: $Exports<'uikit/src/js/components/sortable'>;
}
declare module 'uikit/src/js/components/tooltip.js' {
  declare module.exports: $Exports<'uikit/src/js/components/tooltip'>;
}
declare module 'uikit/src/js/components/upload.js' {
  declare module.exports: $Exports<'uikit/src/js/components/upload'>;
}
declare module 'uikit/src/js/core/accordion.js' {
  declare module.exports: $Exports<'uikit/src/js/core/accordion'>;
}
declare module 'uikit/src/js/core/alert.js' {
  declare module.exports: $Exports<'uikit/src/js/core/alert'>;
}
declare module 'uikit/src/js/core/cover.js' {
  declare module.exports: $Exports<'uikit/src/js/core/cover'>;
}
declare module 'uikit/src/js/core/drop.js' {
  declare module.exports: $Exports<'uikit/src/js/core/drop'>;
}
declare module 'uikit/src/js/core/dropdown.js' {
  declare module.exports: $Exports<'uikit/src/js/core/dropdown'>;
}
declare module 'uikit/src/js/core/form-custom.js' {
  declare module.exports: $Exports<'uikit/src/js/core/form-custom'>;
}
declare module 'uikit/src/js/core/gif.js' {
  declare module.exports: $Exports<'uikit/src/js/core/gif'>;
}
declare module 'uikit/src/js/core/grid.js' {
  declare module.exports: $Exports<'uikit/src/js/core/grid'>;
}
declare module 'uikit/src/js/core/height-match.js' {
  declare module.exports: $Exports<'uikit/src/js/core/height-match'>;
}
declare module 'uikit/src/js/core/height-viewport.js' {
  declare module.exports: $Exports<'uikit/src/js/core/height-viewport'>;
}
declare module 'uikit/src/js/core/hover.js' {
  declare module.exports: $Exports<'uikit/src/js/core/hover'>;
}
declare module 'uikit/src/js/core/icon.js' {
  declare module.exports: $Exports<'uikit/src/js/core/icon'>;
}
declare module 'uikit/src/js/core/index.js' {
  declare module.exports: $Exports<'uikit/src/js/core/index'>;
}
declare module 'uikit/src/js/core/leader.js' {
  declare module.exports: $Exports<'uikit/src/js/core/leader'>;
}
declare module 'uikit/src/js/core/margin.js' {
  declare module.exports: $Exports<'uikit/src/js/core/margin'>;
}
declare module 'uikit/src/js/core/modal.js' {
  declare module.exports: $Exports<'uikit/src/js/core/modal'>;
}
declare module 'uikit/src/js/core/nav.js' {
  declare module.exports: $Exports<'uikit/src/js/core/nav'>;
}
declare module 'uikit/src/js/core/navbar.js' {
  declare module.exports: $Exports<'uikit/src/js/core/navbar'>;
}
declare module 'uikit/src/js/core/offcanvas.js' {
  declare module.exports: $Exports<'uikit/src/js/core/offcanvas'>;
}
declare module 'uikit/src/js/core/responsive.js' {
  declare module.exports: $Exports<'uikit/src/js/core/responsive'>;
}
declare module 'uikit/src/js/core/scroll.js' {
  declare module.exports: $Exports<'uikit/src/js/core/scroll'>;
}
declare module 'uikit/src/js/core/scrollspy-nav.js' {
  declare module.exports: $Exports<'uikit/src/js/core/scrollspy-nav'>;
}
declare module 'uikit/src/js/core/scrollspy.js' {
  declare module.exports: $Exports<'uikit/src/js/core/scrollspy'>;
}
declare module 'uikit/src/js/core/sticky.js' {
  declare module.exports: $Exports<'uikit/src/js/core/sticky'>;
}
declare module 'uikit/src/js/core/svg.js' {
  declare module.exports: $Exports<'uikit/src/js/core/svg'>;
}
declare module 'uikit/src/js/core/switcher.js' {
  declare module.exports: $Exports<'uikit/src/js/core/switcher'>;
}
declare module 'uikit/src/js/core/tab.js' {
  declare module.exports: $Exports<'uikit/src/js/core/tab'>;
}
declare module 'uikit/src/js/core/toggle.js' {
  declare module.exports: $Exports<'uikit/src/js/core/toggle'>;
}
declare module 'uikit/src/js/core/video.js' {
  declare module.exports: $Exports<'uikit/src/js/core/video'>;
}
declare module 'uikit/src/js/icons.js' {
  declare module.exports: $Exports<'uikit/src/js/icons'>;
}
declare module 'uikit/src/js/mixin/class.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/class'>;
}
declare module 'uikit/src/js/mixin/index.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/index'>;
}
declare module 'uikit/src/js/mixin/modal.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/modal'>;
}
declare module 'uikit/src/js/mixin/position.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/position'>;
}
declare module 'uikit/src/js/mixin/slideshow.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/slideshow'>;
}
declare module 'uikit/src/js/mixin/togglable.js' {
  declare module.exports: $Exports<'uikit/src/js/mixin/togglable'>;
}
declare module 'uikit/src/js/uikit-core.js' {
  declare module.exports: $Exports<'uikit/src/js/uikit-core'>;
}
declare module 'uikit/src/js/uikit.js' {
  declare module.exports: $Exports<'uikit/src/js/uikit'>;
}
declare module 'uikit/src/js/util/dom.js' {
  declare module.exports: $Exports<'uikit/src/js/util/dom'>;
}
declare module 'uikit/src/js/util/env.js' {
  declare module.exports: $Exports<'uikit/src/js/util/env'>;
}
declare module 'uikit/src/js/util/fastdom.js' {
  declare module.exports: $Exports<'uikit/src/js/util/fastdom'>;
}
declare module 'uikit/src/js/util/index.js' {
  declare module.exports: $Exports<'uikit/src/js/util/index'>;
}
declare module 'uikit/src/js/util/lang.js' {
  declare module.exports: $Exports<'uikit/src/js/util/lang'>;
}
declare module 'uikit/src/js/util/mouse.js' {
  declare module.exports: $Exports<'uikit/src/js/util/mouse'>;
}
declare module 'uikit/src/js/util/options.js' {
  declare module.exports: $Exports<'uikit/src/js/util/options'>;
}
declare module 'uikit/src/js/util/player.js' {
  declare module.exports: $Exports<'uikit/src/js/util/player'>;
}
declare module 'uikit/src/js/util/position.js' {
  declare module.exports: $Exports<'uikit/src/js/util/position'>;
}
declare module 'uikit/src/js/util/touch.js' {
  declare module.exports: $Exports<'uikit/src/js/util/touch'>;
}
declare module 'uikit/tests/js/index.js' {
  declare module.exports: $Exports<'uikit/tests/js/index'>;
}
declare module 'uikit/tests/js/uikit.js' {
  declare module.exports: $Exports<'uikit/tests/js/uikit'>;
}
declare module 'uikit/webpack.config.js' {
  declare module.exports: $Exports<'uikit/webpack.config'>;
}
